### ISSUE TITLE
Choose a language for our project.

### ISSUE THREAD

**Issue by OlehKSS** [OlehKSS/IMMAS#1]
We need to decide which programming language is better for our project.

I think the main options are:
* C++
* Python

I personally  prefer Python for these reasons:
* we will need to do machine learning, and I think there are more tools for this in Python, than in C++
* it will be possible to use numpy and its matlab like functions
* we can use Jupyter-notebooks for presentation and testing
* it will be easier to install Opencv and other libraries via conda
* we will be have no need to do compilation, typechecking 
* @briannaburton1 will be able to work directly on her notebook, without virtual machine

I have asked Bria about Python, and he said it would be ok to use it. We can send him an email in order to get his permission.

Would do you think @briannaburton1 , @marcioabcr?

**Comment by marcioabcr** [comment]
I know more C++ than Python, but this migth be a good possibility to learn more about Python, since it's a language that we will need to learn and we'll use next semester.
I think that Python could be a good ideia.

**Comment by briannaburton1** [comment]
I prefer Python but I just want to be sure we have discussed it with Bria.

**Comment by briannaburton1** [comment]
Also @OlehKSS I already have C++ and Python installed working with OpenCV on my mac so it's not a problem for me
