### ISSUE TITLE
Make a project plan

### ISSUE THREAD

**Issue by OlehKSS** [OlehKSS/IMMAS#2]
I converted your note to an issue, @briannaburton1, so we will be able to do a discussion here.

This is what Bria proposed for us:
1.  preprocessing, e.g. contrast enhancement with one of the techniques learnt from Image Processing
2.  mass candidate extraction, e.g. oversegmentation with one of the techniques learnt from AIA
3. feature extraction  - extract a set of meaningful features from each mass candidate (features learnt from AIA + others)
4. classification - use machine learning (SVM, Boosting, Random Forest, ... others learnt from Pattern Recognition) to classify candidates into masses and nonmasses

What do you think, @briannaburton1 , @marcioabcr ?

**Comment by briannaburton1** [comment]
@OlehKSS that's not a project plan...it's a method. We need something we can actually approach, like figuring out how to do those things and design our project. Every article I have read so far follows that method.

**Comment by briannaburton1** [comment]
@OlehKSS you are having too much fun with these labels

**Comment by OlehKSS** [comment]
@briannaburton1 I have just put just something to start with. Yep, labels are cool
