### ISSUE TITLE
extraction of the segmented regions and feature extraction

### ISSUE THREAD

**Issue by briannaburton1** [OlehKSS/IMMAS#51]
Read the article [A New Local Adaptive Mass Detection Algorithm in Mammograms](https://github.com/OlehKSS/IMMAS/blob/master/Articles/A%20New%20Local%20Adaptive%20Mass%20Detection%20Algorithm%20in%20Mammograms.pdf).

Check other articles if needed.
Define features for our masses.
Check feature that Bria suggested: **local binary patterns**.

Output should be a function that will return a feature array for a given image. At the same time we should be able to extract

**Comment by OlehKSS** [comment]
@doiriel, please write your findings on Local Binary Patterns as a comment to this issue.

**Comment by OlehKSS** [comment]
**Features that we can use for our classifier**:
* perimeter of the region
* area of the region
* circularity = P^2 / 4*pi*A, where P is circumference (perimeter of the region), A is area of the region.
* AC ratio = Area/Circularity, it is used to filter curve-linear structures such as blood vessels and milk ducts in mammogram.
