### ISSUE TITLE
Where should true positive data come from?

### ISSUE THREAD

**Issue by OlehKSS** [OlehKSS/IMMAS#68]
Now we have our segmentation method and true positive mask.

Should we calculate mass region features based on which segmentation, from our method or using ground truth result? Now we take features from ground truth result.

This data will be used only for training purposes. If we take features from ground truth our classifier will lean more accurate data. But we will not take into account our classifier output.

Ask professor Bria.

**Comment by marcioabcr** [comment]
In the article "An Efficient Approach for Automated Mass Segmentation and Classification in Mammograms", the authors seem to use the ground truth to get the features.

**Comment by OlehKSS** [comment]
Bria suggested to use results of our classifier for the training, use Jackard index in order to find correspondence with masses and candidate regions. We should define minimum threshold for the correspondence, around 0.2, it can be used as one of the parameters for ROC curve calculations.
